spring:
  application:
    name: spring-boot-activemq
  activemq:
    broker-url: tcp://localhost:61616  # ActiveMQ????
    user: admin                        # ????????
    password: admin                    # ???????
  jms:
    pub-sub-domain: false              # ???????true???????

# ???????
demo:
  queue: spring-boot-queue